version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: jjunior-stremio_server_1
      APP_PORT: 8080

  server:
    image: tsaridas/stremio-docker:v1.2.10@sha256:37abbbc5116a4d256bceddff4710015ad0132db0cd857c97723959148d7abb73
    ports:
      - 11470:11470 #HTTP
      - 12470:12470 #HTTPS
    environment:
      - NO_CORS=1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/root/.stremio-server
